### ISSUE TITLE
need unified Pattern

### ISSUE THREAD

**Issue by ByReaL** [open-traffic-generator/abstract-python-package#10]
I see device.py and flow.pyfrom ...\abstract_open_traffic_generator have Pattern defined, code looks almost similar but not quite the same.

will be good if we could have a unified Pattern object in the end if I configure the IP on an interface or in a packet I could make use of the same pattern object.

also if we follow the samples and do 
```
from abstract_open_traffic_generator.flow import *
from abstract_open_traffic_generator.device import *
```
it creates confusion on what Pattern is imported

and doing like this for Pattern, counter, random,..... seems too much of a hassle.
```
from abstract_open_traffic_generator.device import Pattern as DevicePattern
from abstract_open_traffic_generator.flow import Pattern as FlowPattern
```

ipv4,vlan..will suffer for same name collisions even if code is different and may not make sense to consolidate in a generic ipv4 VLAN object

**Comment by ajbalogh** [comment]
patterns are driven by the models - in the models the flow field pattern has a count while the device pattern does not
