### ISSUE TITLE
Stats Tx_Bytes/Rx_Bytes are required. Only Tx_Farme/Rx_frame is not enough.

### ISSUE THREAD

**Issue by abhijit-dhar** [open-traffic-generator/abstract-python-package#3]
In Flow Statistics Tx_Bytes/Rx_Bytes are required. Only Tx_Farme/Rx_frame is not enough.
We want to calculate estimated bytes to be received at the RX end, and match that should closely match actual Rx byte within certain tolerance. Something like below.

TOLERANCE_THRESHOLD = .98
exp_tx_bytes = (exp_dur * port_bw * 1000000 * (RATE_PERCENTAGE / 100.0)) / 8
tolerance_ratio = rx_bytes / exp_tx_bytes
if ((tolerance_ratio < TOLERANCE_THRESHOLD) or (tolerance_ratio > 1)) :
     assert(False)

**Comment by ajbalogh** [comment]
bytes_rx, bytes_tx are supported in the model.
bytes_rx is supported in the concrete ixnetwork implementation
bytes_tx is not supported in concrete ixnetwork implementation (not even supported in ixnetwork).
