### ISSUE TITLE
fixed duration traffic is required. I want to start traffic but that should stop after a given seconds (say 3) automatically

### ISSUE THREAD

**Issue by abhijit-dhar** [open-traffic-generator/abstract-python-package#4]
**See the diagram below:**

![image](https://user-images.githubusercontent.com/67135817/94430543-b906c580-01b1-11eb-850c-27d98b530236.png)

**Comment by ajbalogh** [comment]
Is this an actual requirement from one of the sonic test cases?
The reason is because the traffic generator does not actually support an accurate 3 second duration  but makes an best effort attempt to calculate the number of pps using framesize, port speed and preamble.

**Comment by abhijit-dhar** [comment]
Sonic team requires a mechanism to calculate stats independent of Ixia stats (expected_rx_bytes). And want to match that with actual_rx_byte (may be ixia stat). Here expected_rx_bytes = (port_bw * line_rate * traffic_duration)/8. 

actual_rx_byte  should not exceed  expected_rx_bytes. But the ratio actual_rx_byte/expected_rx_bytes should be near to 1 but less than 1. say .97 <=  actual_rx_byte/expected_rx_bytes <= 1. [should not be bigger than one]

if we do "start_traffic-->sleep->stop_traffic" or "start_traffic-->sleep->get_stats" the above ratio becomes bigger than 1. The time taken by stop_traffic or get_stats takes time, and in the mean time some more frame gets transmitted and received. The time taken by stop_traffic or get_stats grossly remains uncalculated, and thus the frames send/received in that interval.

**One way to make the ratio to close to one, but less than one is to increase the transmission duration so that time taken by  stop_traffic or get_stats become negligible compared to transmission duration**. Following is the statistics (transmission duration --> (actual_rx_byte/expected_rx_bytes) ratio.  As the transmission duration increases the ratio become close to 1 because percentage of error reduces. We could reduce the run duration if traffic is stopped exactly after 3 (or any given second)
duration --> (actual_rx_byte/expected_rx_bytes)
-----------------------------------------------------
1 --> 14.686059561
5 --> 2.88703299584
10 --> 1.84094456218
15 --> 1.63310336956
20 --> 1.32288041779
25 --> 1.37214750884
30 --> 1.27430767411
35 --> 1.30848560157
40 --> 1.2009164759
45 --> 1.24182968548
50 --> 1.19615378555
55 --> 1.15871612034
60 --> 1.12419801771
65 --> 1.12701034181
70 --> 1.10660406243
75 --> 1.10510199712
80 --> 1.09087766938
85 --> 1.09591025495
90 --> 1.07866173349
95 --> 1.08383382129
100 --> 1.06683215872
105 --> 1.07400907669
110 --> 1.06086019891
115 --> 1.06589840856
120 --> 1.05250749372
125 --> 1.05912601936
130 --> 1.04699428738
135 --> 1.05330467726
140 --> 1.04224657174
145 --> 1.04831481305
150 --> 1.05259859859
155 --> 1.04253806156
160 --> 1.03426232627
165 --> 1.03893739408
170 --> 1.03262541463
175 --> 1.03445529887
200 --> 1.03214464369

**Comment by ajbalogh** [comment]
closed and moved to ixnetwork repository
